matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: rust
      rust: nightly
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo test --verbose
  allow_failures:
    - rust: beta
    - rust: stable

sudo: required

dist: trusty

group: edge

